package hibernate.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PackageDetails generated by hbm2java
 */
public class PackageDetails  implements java.io.Serializable {


     private Integer packageDetailsId;
     private String packageName;
     private Set packageTransactions = new HashSet(0);

    public PackageDetails() {
    }

	
    public PackageDetails(String packageName) {
        this.packageName = packageName;
    }
    public PackageDetails(String packageName, Set packageTransactions) {
       this.packageName = packageName;
       this.packageTransactions = packageTransactions;
    }
   
    public Integer getPackageDetailsId() {
        return this.packageDetailsId;
    }
    
    public void setPackageDetailsId(Integer packageDetailsId) {
        this.packageDetailsId = packageDetailsId;
    }
    public String getPackageName() {
        return this.packageName;
    }
    
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }
    public Set getPackageTransactions() {
        return this.packageTransactions;
    }
    
    public void setPackageTransactions(Set packageTransactions) {
        this.packageTransactions = packageTransactions;
    }
}
